### PR TITLE
Update to icony-angular to allow Angular 11

### PR DESCRIPTION
**Pull request by mokipedia**
## PR Type

What kind of change does this PR introduce?

Adds the possibility to override parameter codec per request

```
[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[X] Refactoring (no functional changes, no api changes)
[X] Build related changes
[ ] CI related changes
[ ] Documentation content changes
[ ] Other... Please describe:
```

## What is the current behavior?

iconify-angular peer dependencies do not include angular 11

## What is the new behavior?

- iconify-angular peer dependencies allow all new angular versions above 5.0.0 so updating this lib with every major version is not necessary anymore.

## Does this PR introduce a breaking change?

```
[ ] Yes
[X] No
```

## Other information

- update to angular 11 for app
- tests should be fixed
- if "all above v5.0.0" is not to your liking, I would suggest making a cut with old supported versions.

### CODE REVIEW

**Comment by mokipedia** [comment]
accidentally pushed with wrong email, force-pushed
added comment which test icon, squashed & force-pushed again

**Comment by mokipedia** [comment]
if peerDependency "all above v5.0.0" for @angular in https://github.com/visurel/iconify-angular/pull/14/commits/e2a1a36f7c9d0bef1d882be94f6757ca10f6e1c6 is not to your liking, I would instead suggest making a cut with version 11 of this lib and support old versions with 10.x while supporting 11+ with v11 of this lib. Otherwise the versions string will get messy and it is most likely untested for older versions anyway.

if you want me to just add angular@11, pls tell me so and I will change it back.

**Comment by visurel** [comment]
Thanks for the PR! I'll try to have a look at it in the next days and merge it. 👍

**Comment by mokipedia** [comment]
ping

**Comment by visurel** [comment]
Just published v11.0.0 🚀

**Pull request merged**
